# Uses https://github.com/vaggeliskls/docusaurus-to-pdf?tab=readme-ov-file#example-workflow
name: "Generate PDF from Docusaurus"

on:
  push:

jobs:
  generate-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Docusaurus to PDF Action
        uses: vaggeliskls/docusaurus-to-pdf@v1
        with:
          DOCS_URL: "https://www.oramainteractive.com/Pixelorama-Docs"

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Docusaurus-PDF
          path: "Pixelorama-Docs.pdf"
          if-no-files-found: error
